dist: trusty
sudo: false
language: python
python:
  - "3.6"
install:
  - "pip install -Ur requirements/test_reqs.txt"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - "psql -c 'create database hifumi_testing;' -U postgres"
script:
  - pytest translations/tests
  - pytest tests/
after_script:
  - "wget https://raw.githubusercontent.com/MaT1g3R/travis_discord/master/travis.sh"
  - "bash travis.sh"
notifications:
  email: false
