language: python
python:
  - "3.6"
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos*
install:
  - "pip install -r requirements.txt"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - "psql -c 'create database hifumi_testing;' -U postgres"
script: pytest
notifications:
  email:
    - neovisatoons@gmail.com
    - mat1g3r@gmail.com
